USE customer_behavior_db;

SELECT * FROM customer_table;

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender, sum(purchase_amount) as revenue
FROM customer_table
GROUP BY gender;

-- Q2 Which customer used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer_table
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_table);

-- Q3 Which are the top 5 products with the highest average review rating 

SELECT item_purchased, ROUND(AVG(review_rating),2) as average_review_rating 
FROM customer_table
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

SELECT * FROM customer_table;

-- Q4 compare the average purchase amounts between standard and express shipping.

SELECT shipping_type, ROUND(AVG(purchase_amount),2) as average_purchase_amounts
FROM customer_table
WHERE shipping_type in ('standard','express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, COUNT(customer_id) as total_customers, AVG(purchase_amount) as average_spend , SUM(purchase_amount) as total_revenue
FROM customer_table
GROUP BY subscription_status;
  
-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, 
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
FROM customer_table
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment
-- with the help of CTE

WITH customer_type as (
SELECT 
CASE 
     WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning' 
	 ELSE 'Loyal'
     END AS customer_segment
FROM customer_table
)

SELECT customer_segment, COUNT(*) as 'Number of customers'
FROM customer_type
GROUP BY customer_segment;

SELECT * FROM customer_table;

-- Q8 What are the top 3 most purchased products within each category?

With item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
DENSE_RANK() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer_table
GROUP BY category , item_purchased)

SELECT item_rank, category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,COUNT(customer_id) as repeat_buyers
FROM customer_table
WHERE previous_purchases >5
GROUP BY subscription_status;

-- Q10 What is the revenue contribution by age group?

SELECT age_group,SUM(purchase_amount) as revenue_contribution
FROM customer_table
GROUP BY age_group
ORDER BY revenue_contribution DESC;

